.github/workflows/main.yml
Entitlements are established, updated publish command to version v0.0.3, and set as release to build to proper code signing, notarization, and entitlements.
=> Entitlements & v0.0.3 Publish Update

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/windows.rs, src/lib/autoLaunch/macAutoLaunch.ts, src/lib/autoLaunch/nullAutoLaunch.ts, src/lib/autoLaunch/winAutoLaunch.ts, src/lib/native.ts, yarn.lock
Created fresh PR with clean history after squash
=> Windows autolaunch

ARCHITECTURE.md, README.md, src/layouts/MainLayout.vue, src/lib/native.ts
Added ARCHITECTURE.md which provides an overview of the app design.
=> Documentation

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src/components/SaveKeys.vue, src/lib/client.ts, src/pages/SetupPlot.vue
This PR extracts the mnemonic from the farmer lib from the tauri backend, and uses it in the desktop app
=> mnemonic support added to desktop app

.github/workflows/publish.yml, src-tauri/Cargo.lock, src-tauri/Cargo.toml
After the update on `subspace-network`, tests are passing!
Also a small fix to `publish.yml` that I missed on the previous PR.
=> Publish ci fix

.github/workflows/publish.yml
Tried the `publish` workflow, figured out these typos and also put the updates that I made to ci-tests to `publish.yml`.
Tested the workflow, appears to be working. Will initiate the publish workflow on main branch after this PR is merged.
=> publish typos

src/components/SaveKeys.vue, src/lib/client.ts, src/pages/Error404.vue, src/pages/PlottingProgress.vue
=> Front end - remove mnemonic from LocalStorage

.github/workflows/publish.yml
This will close issue #67 
Simple fix.
=> Remove App-V from release

package.json, src-tauri/Cargo.toml
I will trigger the release build after this PR. 
For the next iterations, I will not make a separate PR for these, and include these version changes into the last relevant PR.
=> bump version to 0.2.0

README.md
Nothing major, just added a how to install section for users
=> Update: Readme, added how to install section.

src/pages/PlottingProgress.vue
Keep in mind that I'm not experienced in JS, and the changes in this PR may not be following the best practices. 
This PR aims to fix #72
After you guys approve/improve what I've done here, I will remove the commented out parts.
=> make farmer and nodesync concurrent

.env, src/components/mainMenu.vue, src/lib/autoLauncher.ts
Fixes #75 
Tested on all 3 major platforms, works for my machines.
=> Launch on boot

README.md
trivial PR. 
Feel free to update/fix it.
=> Documentation revamp

src/lib/appConfig.ts, src/lib/autoLauncher.ts, src/lib/global.ts, src/lib/util.ts, src/pages/Index.vue, src/pages/PlottingProgress.vue, src/pages/SetPassword.vue, src/pages/SetupPlot.vue
=> remember autoLaunch preference

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml
bumping version because of 3 minor changes: 
- logo fix
- dont show mnemonic if reward address is entered
- notification for autolaunch
=> version bump 0.3.1

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src/lib/client.ts, src/lib/util.ts, src/pages/Dashboard.vue, src/pages/Index.vue
This PR will make the desktop app disconnect from the PublicRPC once the connection is not needed.
Please refer to the comments below for additional details
=> Drop public rpc connection

src/components/disclaimer.vue, src/pages/Index.vue
Here is the new disclaimer:
This appears before the main functionality begins (both for quick start and advanced).
=> Testnet disclaimer

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/farmer.rs, src-tauri/src/main.rs, src-tauri/src/node.rs, src/components/SaveKeys.vue, src/components/farmedList.vue, src/lib/appConfig.ts, src/lib/autoLauncher.ts, src/lib/client.ts, src/lib/types.ts, src/lib/util.ts, src/loc/en.json, src/pages/ImportKey.vue, src/pages/Index.vue, src/pages/SetupPlot.vue
Creating as a draft PR at the moment. 
When we do the runtime upgrade on the monorepo side, I will remove the custom chainspec file from here, and turn it into a real PR
=> Multi replica

README.md
First iteration for the README -> OS specs. 
Nothing fancy, but feel free to improve/better it
=> Readme os specs

src-tauri/src/node.rs
=> windows cors issue fix

src/loc/en.json, src/pages/Index.vue
=> Update translation and styles for the welcome page

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/src/node.rs, src-tauri/tauri.conf.json, src/components/farmedList.vue, src/lib/appConfig.ts, src/lib/appData.ts, src/lib/applescript.ts, src/lib/autoLauncher.ts, src/lib/blockStorage.ts, src/lib/client.ts, src/lib/native.ts, src/lib/util.ts, src/pages/Dashboard.vue, src/pages/Index.vue, src/pages/PlottingProgress.vue, src/pages/SetupPlot.vue
trivial logging architecture for logging.
useful information for reviewing this PR:
- it is using a native plugin from tauri team for logging: https://github.com/tauri-apps/tauri-plugin-log
- backend exposes two new functions for logging to the frontend (1 for error, 1 for info level)
- frontend uses these exposed functions to relay the error/log messages to backend
- tauri handles all the process of writing logs to an external file
- external log file location is not configurable from the end-user perspective. We are using the default ones for macos, linux and windows respectively (actually, tauri-plugin-log is handling these)
I suggest reviewing commit by commit
P.S. 
I changed the identifier name from `com.tauri.dev` to `com.subspace.desktop`
=> Logging and small fixes

package.json, src/boot/init.ts, src/components/SaveKeys.vue, src/components/farmedList.vue, src/components/mainMenu.vue, src/components/netCard.vue, src/components/plotCard.vue, src/layouts/MainLayout.vue, src/lib/appConfig.ts, src/lib/autoLauncher.ts, src/lib/blockStorage.ts, src/lib/client.ts, src/lib/global.ts, src/lib/util.ts, src/pages/Dashboard.vue, src/pages/ImportKey.vue, src/pages/Index.vue, src/pages/PlottingProgress.vue, src/pages/SetupPlot.vue, tsconfig.json, yarn.lock
- update dependencies
- fix cannot read private member #isReadyPromise
- adjust TS and Eslint
=> Fix cannot read private member #isReadyPromise and dependencies update

src/boot/init.ts, src/components/mnemonicModal.vue, src/lib/appConfig.ts, src/lib/client.ts, src/lib/types.ts, src/pages/Dashboard.vue, src/pages/Index.vue, src/pages/PlottingProgress.vue, src/pages/SetupPlot.vue
- remove connection to Public RPC node
- remove segments and blockchain size - show synced blocks instead
- mnemonic modal clean up
=> 182 receive peers and block information from node

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
Very trivial PR. 
Still, I put some comments below to put light onto changes and their reasonings
=> Conventional log folders

.github/workflows/ci-tests.yml, .github/workflows/publish.yml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/farmer.rs, src-tauri/src/main.rs, src-tauri/src/node.rs, src/lib/client.ts, src/lib/util.ts, src/pages/PlottingProgress.vue
This PR updates the dependencies for monorepo
=> Monorepo dependencies update

src-tauri/src/node.rs
=> Allow unsafe RPC methods

package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src/components/plotCard.vue, src/lib/appConfig.ts, src/lib/util.ts, src/pages/SetupPlot.vue
=> plot card render bug fixed

src-tauri/src/node.rs
It was default in desktop app already, so no need to make it more complicated than it should be.
Also see https://github.com/subspace/subspace/issues/508 fro wider context.
=> Unconditionally use ParityDB

src-tauri/src/main.rs
=> Start Devtools programmatically in dev

package.json, src-tauri/Cargo.toml
Update to reflect latest update in Subspace Desktop
=> Updated cargo to reflect to june-03 rev, updated version to 0.6.2

src/pages/SetupPlot.vue
Long-awaited support for external drives is here :)
It was more trivial than I thought :D
=> added support for external drives

src/lib/client.ts, src/pages/PlottingProgress.vue
In order to close #264 we'll need to update mockups so that UI properly reflects when the app transitions from `synced` to s`syncing`
=> use system.health to get isSyncing status

src-tauri/Cargo.lock, src-tauri/Cargo.toml
See the last comment in: https://github.com/subspace/subspace-desktop/issues/272
Fixes #272
=> vendored openssl

src/components/SaveKeys.vue, src/components/mnemonicModal.vue, src/lib/client.ts, src/pages/SetupPlot.vue
Pass mnemonic as a component prop only once instead of storing and removing it on unmount
=> Small mnemonic modal update

src-tauri/src/node.rs
Mirrors https://github.com/subspace/subspace/pull/692
=> Increase default number of outgoing peers

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/farmer.rs
see: https://github.com/subspace/subspace/pull/721
=> reflect monorepo fix

.github/workflows/ci-tests.yml, .github/workflows/discord.yml
we will be able to do this automatically after this workflow
=> discord workflow improvements

src/i18n/en.json, src/lib/client.ts, src/lib/native.ts, src/lib/util/tauri.ts, src/pages/Index.vue, src/stores/store.ts
Some minor refactoring and updates, including a fix for the bug when the app did not reset properly
=> Minor improvements

src-tauri/src/node.rs
=> replace discord invite with permanent forum link
