.github/workflows/ci-tests.yml

This should only be included with Publish and was pinging apple for notarization upon every push, & pull_request

updated ci-tests to no longer code-sign and notarize

---

.github/workflows/ci-tests.yml
.github/workflows/publish.yml

This updates the `publish.yml`. 
Right now, `publish.yml` is outdated, so we need to update it for releasing the desktop-app.
We also don't want regular CI jobs to trigger when `yml` files are edited. The reason is, yaml file changes only take effect when they are merged into main. So running the current tests when a `yml` file changes provides no extra information to us, just wastes time.
pre-release is set to true, I will change it back to `false` when we successfully integrate the node, and the desktop-app can be a standalone farming application.

Publish update

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/build.rs
src-tauri/chain-spec-raw.json
src-tauri/chain-spec.json
src-tauri/rust-toolchain.toml
src-tauri/src/build.rs
src-tauri/src/main.rs
src-tauri/src/node.rs
src/loc/en.json

This removes both `subspace-node` and `sc-cli` from dependencies since we want to run subspace node as a library, not as CLI application.
Have not tested this, but I think it should work. Chain spec might need to be modified to include correct bootstrap node, `FORCE_AUTHORING` environment variable can be used to force authoring. I also had to do a few minor tweaks.
Makes https://github.com/subspace/subspace/pull/274 unnecessary.

Node integration without CLI

---

.github/workflows/ci-tests.yml
.github/workflows/publish.yml
package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

Seems to work fine both on Windows 10 and WIndows 11, so we're switching monorepo to only build under Windows 2022, let's make the same here unless you are aware of any issues this may cause.

Switch CI to Windows 2022

---

.github/workflows/publish.yml
package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/entitlements.plist

macos signing now works (also thanks to @ImmaZoni for his suggestion).
Fixes #93 
Not important: publish.yml was creating some warnings due to `body` and `draft` are not recognized in the `tauri run` job.
They should be `releaseBody` and `releaseDraft`. Check the link below for confirmation on this:
https://github.com/tauri-apps/tauri-action

Macos sign fix

---

.env
.github/workflows/ci-tests.yml
.github/workflows/publish.yml
package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/entitlements.plist
src-tauri/rust-toolchain.toml
src-tauri/src/main.rs
src-tauri/tauri.conf.json
src/lib/applescript.ts
src/lib/util.ts
yarn.lock

I considered downgrading `zstd` version in a fork, but the simpler solution for now is to just disable compression.
Compression wasn't there before in Tauri (at least there was no such feature) and Debian package size got much smaller after upgrade anyway (30.2M -> 22.7M).

Upgrade Tauri to latest version

---

src/lib/autoLauncher.ts

Should work fine for Debian package, will not work for AppImage, but it didn't work before, so fine.
BTW, I noticed it actually doesn't create the autostart file on Linux for some reason (on 0.2.0).

Fix for Linux autostart icon

---

src/lib/client.ts
src/lib/util.ts
src/pages/Dashboard.vue
src/pages/Index.vue
src/pages/PlottingProgress.vue

- Fixes: #128 
It now gets the value from the `subspace storage`.
Should take less than a second now.

Fix slow plot size estimation.

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src/components/mainMenu.vue
src/lib/appConfig.ts
src/lib/autoLauncher.ts

AutoLaunch bug (not remembering the config) was fixed before. But after local storage changes, it regressed and reappeared. 
The fix was pretty simple (inspect appConfig.ts file). Now it should be fine, and more safe (there are few improvements on `enable` and `disable` functions.
Other than that, the naming was confusing and not making sense for `autoLaunch` related variables in `mainMenu`. 
Lastly, bumped the version to 0.3.0 after massive changes we had recently, and will publish a pre-release after this PR

autoLaunch fix and version bump

---

src/pages/Index.vue

Waiting for #139 to merge (for remembering the LaunchOnBoot preference bug fix)
Fixes #136 .
Did not want to complicate the application by prompting the user for permission on this. Instead, we are notifying the user about the app will be launched on boot, and if wanted, it can be disabled from settings.

notify for autolaunch

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src/components/SaveKeys.vue
src/components/introModal.vue
src/components/mnemonicModal.vue
src/lib/appConfig.ts
src/lib/appData.ts
src/lib/autoLauncher.ts
src/lib/client.ts
src/lib/util.ts
src/loc/en.json
src/pages/ImportKey.vue
src/pages/Index.vue
src/pages/PlottingProgress.vue
src/pages/SetupPlot.vue
yarn.lock

This PR fixes an important flaw in the workflow:
**user may not have displayed mnemonic, and lose the chance of displaying mnemonic ever again**
fixes #164 
fixes #163 
Nazar suggested that we can store the mnemonic in the keychain, but I'm still favouring not storing the mnemonic at all. 
*And even if we decide to store the mnemonic in the keychain, it will be implemented later. And this problem needs to be addressed ASAP imo*. So, in short, this will either be a temporary solution, or a permanent one.
1. user starts the app for the first time
2. proceeds to plotting screen
3. in plotting screen, the user does not display the intro (hence, mnemonic is not shown)
4. user quits the app for god knows why
5. when user re-opens the app, it goes directly to the dashboard, because the config is …

mnemonic workflow fixed

---

src-tauri/src/main.rs
src/components/farmedList.vue
src/components/mainMenu.vue
src/lib/appConfig.ts
src/lib/autoLauncher.ts
src/lib/client.ts
src/lib/types.ts
src/lib/util.ts
src/pages/Dashboard.vue
src/pages/ImportKey.vue
src/pages/Index.vue
src/pages/PlottingProgress.vue
src/pages/SetupPlot.vue

This PR revamps the address structure (publicKey and rewardAddress). 
Changes:
- the farmer returns the publicKey instead of the node
- and since we unified the workflow of providing a reward address always to the farmer, `farming` function is also simplified.
- Node does not return anything anymore. 
- the publicKey address formatting on the frontend is simplified.
- reward address related optimizations on frontend

address structure is fixed

---

src/components/mainMenu.vue

Disables the `reset` button from the main menu (which removes everything and basically performs a soft uninstall-reinstall) for the production mode. And keeps it only for the dev mode.
The motivation behind this is: and accidental click on this button (although there is a confirmation screen) can be very upsetting for the end users, and it serves more purpose for the dev env.

disabled reset button on prod

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml

After fixing the bugs on 0.4.1, lets bump the version and release a stable one.
Multi-replica release may take time to become stable, so this is a good stepping stone between stable releases

version bump to 0.4.2

---

.github/workflows/ci-tests.yml
package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-tauri/tauri.conf.json
src/layouts/MainLayout.vue
yarn.lock

Upgraded tauri to latest version (required for enabling the logger plugin they have).
The next PR will be about external log file mechanism.
Along the way, fixed a small issue: removed the round icon from `MainLayout`. 
The main reason for this is: when `node name` is too long, this round icon overflows to the next line, making the UI very ugly.
The second reason is: it is not very clear what does this icon do from the end-user perspective, and the application will be more minimalistic without it.

upgraded tauri, and removed the round icon from mainlayout

---

src/layouts/MainLayout.vue
src/lib/autoLauncher.ts
src/pages/ImportKey.vue
src/pages/Index.vue
src/pages/SetupPlot.vue

This PR:
- improves the logging messages
- puts some forgotten `await`s in place related to `config.update`
- when imported mnemonic, or when there is a leftover reward address from previous run, it was not setting/updating `plot` config, this is fixed now. This issue is present in main, and also in 0.4.8.
Fixes #203

better logging, and logic fix

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-tauri/src/node.rs
src/lib/appConfig.ts
src/lib/client.ts
src/lib/util.ts
src/pages/Dashboard.vue
src/pages/Index.vue
src/pages/PlottingProgress.vue
src/pages/SetupPlot.vue
yarn.lock

Fixes #197 
Also, refactors some frontend code such that the changed functions have more specific roles and they are better structured.
Lastly, `update` function for config was not `awaiting` on the `write` call to the filesystem. This was creating an edge case, where user closes the modal for viewing mnemonic (view mnemonic modal writes to config on dismiss). And after on dismiss, we are proceeding into `plottingProgress` page.
If the user closes the app immediately after proceeding into `plottingProgress` page, they will expect their reward address to be remembered. But the app sometimes may not have chance to write the `rewardAddress` to the config, since the write operation is not awaited on.
When the `write` operation is awaited, we will not proceed into `plottingProgress` page …

Persistent node name

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
src/lib/appData.ts
src/lib/client.ts
yarn.lock

This fixes the issue of not being able to generate a keyring with `sr25519` type.
This PR also makes our CSP more strict. To my testing, making it stricter did not create any issue. 
I followed Fabian's suggestions and made a small change on it: https://github.com/tauri-apps/tauri/issues/4160#issuecomment-1130363459
The small change: `style-src 'unsafe-inline' 'self';` -> this means: for css, we are enabling inline scripts execution. 
Actually, our app works without this as well, but becomes more ugly. Here is the difference
with this change:
without this change:
It is not recommended to enable this, I don't know how risky it will be for CSS files. It is up for discussion

Fix csp for wasm

---

src/layouts/MainLayout.vue

Temporarily disable edit node name until node restart is implemented on the backend

disable edit name

---

src-tauri/src/main.rs
src/components/farmedList.vue
src/lib/client.ts
src/lib/types.ts
src/pages/Dashboard.vue
src/pages/PlottingProgress.vue

- `Client` module refactoring
- move polkadot/apps link from client to `farmedList` component (since it belongs to presentation logic)
- fetch initial peers count value when Dashboard mounts and increase timeout for refetching
- other minor improvements

Refactoring client

---

src-tauri/src/main.rs
src-tauri/src/utils.rs
src-tauri/tauri.conf.json
src/components/SaveKeys.vue
src/components/mainMenu.vue
src/lib/util.ts
src/loc/en.json

Code-wise -> trivial. 
But it will be wordy to explain the changes.
- 1st change: `reset` button re-added. But changed the wording significantly. Please read the new messages. Any recommendation is welcome
- 2nd change: another button for viewing the logs.
- viewing, not exporting, since I did not want to make the UI cumbersome and pop up many dialogs for where to save the log file, getting permissions and etc. So, as a workaround, when you click `view logs`, it will open the file location of the log file, using the native file explorer for the OS.
- to be able to view the log file, we needed the path to it. I'm not hardcoding the path, but getting it from tauri. 
- we are using tauri's `shell` api to be able to use the native file explorer. And that needs a weird check in the …

Reset and log extraction

---

src-tauri/src/farmer.rs
src-tauri/src/node.rs

It is draft, because we also have to introduce front-end changes. Before that, to eliminate redundant work, I wanted to get your recommendations on whether this approach makes sense to you @nazar-pc and @i1i1.
**Important:** This only includes a restart mechanism for node, not for farmer. I tried the same approach with farmer but could not succeed. Reasons are below. As a workaround, we were already listening for errors on the farmer, and if it crashes (and it will crash during a node restart), we were restarting the farmer. I just added some timeout between the restarts of farmer, giving some time to node to fully restart itself and start listening to farmer.
Reasons why I failed implementing a restart mechanism for farmer is:
- first problem:
- we are waiting on the handle of the farmer …

node-restart mechanism

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/farmer.rs
src-tauri/src/node.rs
src/layouts/MainLayout.vue

Temporary solution for editable node name. 
This PR:
1- reverts the `node-restart` PR, since we have a bug about it (details below)
2- as a workaround, when `node_name` is edited, it calls the `relaunch()` function from tauri. This seems to work on linux and macos. Needs to be tested in windows though.
3- updates the monorepo dependencies as well as Nazar requested.
When node is restarted, the whole application crashes with the error `database file is in use`. This is related to node, not farmer. I debugged it yesterday, and it went deep to `sc_service` crate. Will continue debugging today. 
I suspected it was due to `abort` operation on the `handle` is not completed till we initiate the next instance of node. However, I don't think that is the case. There are 2 reasons:
1- i put 10 …

Editable node name

---

src/pages/Dashboard.vue

After a few complaints, we decided to show the block height again when the node is synced. 
Here how it looks:
I checked on `dev chain`, and it was updating the block heigh value as expected. 
Please check the wording, it may be improved :)

show block height when synced as well

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src/pages/ImportKey.vue

trivial,
also removing a leftover function from old design (related to Import Reward Addres page). We are not using it anymore.
Tested all the functionalities of Import Reward Address just to be sure, everything is working fine as expected.

bump version and update monorepo dependencies

---

src-tauri/tauri.conf.json

Now, the users will be able to resize the application. 
The UI breaks when the dimensions are smaller than `800x600`. So I put some extra limits on that, and the app dimension can't go lower now.
The UI can definitely be optimized for large screens, but at least it does not break, and it can be an optimization for the future.

resizable + minimum dimension limit

---

package.json
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

Fixes #272 
Previously, we were allowing all the `api` provided by tauri. It was not recommended for security reasons anyway. I've checked out the document, and tried to narrow down the scope of the allowlist and csp. 
By removing the `http` from the allowlist, the `openssl` dependency is no longer present. And hence, the bug is resolved.

fix openssl and update allowlist - version bump

---

.github/workflows/ci-tests.yml
.github/workflows/publish.yml
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json

- adds updater to Tauri config
- adds Tauri update keys to GitHub actions workflow
Currently, it will check for updates on the app launch. We still need to clarify UX for periodical checks and dropdown menu item for updates (check for update, install update, etc.)

Tauri updater

---

.github/workflows/publish.yml

Newer Ubuntu uses newer glibc, we need to roll back to 20.04 that used older glibc to make it compatible again. I'm not aware of the way to restrict glibc version used (though I did 0 research, maybe it is in fact possible) and I don't think messing with musl libc is worth it for desktop app either.

Make sure upcoming releases run on Ubuntu 20.04

---

.github/workflows/ci-tests.yml
.github/workflows/publish.yml
src-tauri/Cargo.lock
src-tauri/Cargo.toml
tsconfig.json

Fixes #255 
Fixes #275 
We finally have a new workflow, which allows us to have more granular control over the build process and everything related to executables. The biggest reason was, to be able to publish 2 versions (1 for normal, 1 with opencl).
Note:
Cargo toml changes might seem weird for a workflow PR -> the reason is cirrus-runtime inclusion bug had to be solved on the monorepo side

Workflow update (abandon tauri actions)

---

package.json
src/layouts/MainLayout.vue
src/stores/store.ts
src/tests/store.test.ts
yarn.lock

This is a temporary workaround for #306 while I will be working on a better long-term solution, which will require replacing loop with subscription. The latter can be stopped before the node is restarted and resumed after API is ready
---
closes #306

Add getSyncState retry

---

.github/workflows/discord.yml

Outcome: 
Tested on `discord-testing` channel. 
Nazar provided the webhook for the `prelease-testing` channel, and updated the secret in the repo, so we should be good to go. 
This workflow will be triggered when `publish` is completed, and the jobs will run ONLY IF `publish` is successful.
The message itself is probably not the best, any edit/suggestion is welcomed
---
closes #292

discord workflow

---

src-tauri/tauri.conf.json

This PR is just an update for the Windows Certificate Thumbprint to match the new certificate that has been issued. Secret has been updated already according to @achiurizo

Windows Code Signing Certificate Update 

---

src-tauri/src/farmer.rs
src-tauri/src/main.rs
src-tauri/src/menu.rs
src-tauri/src/node.rs

The existing inline docs on the Rust side were already sufficient. 
I added a few more the make it more comprehensive. 
The code itself is good and does not need much commenting (adding more comments would make it too verbose and unreadable imo). 
I'm open to any suggestions/additions, let me know if you think we need more comments in other places :)
Should close #297

added more inline docs

---

src/i18n/en.json
src/pages/SetupPlot.vue

Add an error message and disable 'Start plotting' button if plot size is more than 100 GB. Closes #322

Add max plot size limit for Gemini II

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs

Previous PR had conflicts with main regarding cargo lock, it was easier to create a new branch on top of the up to date main. 
I made the parameter 7 days for keeping the logs (it was about 24-30 mb daily for my case)

rotating logs and cargo toml cleanup

---

ARCHITECTURE.md
src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src-tauri/src/utils.rs
src-tauri/tauri.conf.json
src/components/mainMenu.vue
src/lib/config.ts
src/lib/util/util.ts
src/pages/Index.vue

We were using `shell.open()` on the frontend to open the log folder (via default OS file explorer). 
This was issue#4 from the audit. 
I made a backend function to handle this, and disabled `shell -> open` access for the frontend. This should fix #338 , and also help #339.
Along the way: 
- I fixed the typos and outdated stuff in the `architecture.md` file, this was mentioned in #340 , so we can complete that sub-task in that issue after this PR merges.
- fixed (9999 - 1000 + 1) 
- fixed weirdly named `checkDev()`
- Duplicate code for config creation

Issue4 and architecture fixes

---

src-tauri/Cargo.toml
src-tauri/src/farmer.rs

@nazar-pc , trail of bits suggested doing these checks at the beginning of the function to reduce side-effects. Thought it might be helpful to the monorepo as well

validate farmer data at the beginning
